// shangguigu/React/react_staging/src/App.js
import React, { Component } from 'react'
import Hello from './components/Hello'
import Welcome from './components/Welcome'

export default class App extends Component {
  state = {name:'小明'}
  add = (params) => {
    console.log(params);
  }
  render() {
    return (
      <div>
        <Hello name={this.state.name} add={this.add} />
        <Welcome />
      </div>
    )
  }
}

// vue/vue3_test/04,setup/App.vue
<template>
  <h1>App</h1>
  <Demo @hello="showInfo" school="复旦大学" subject="电子商务">
    <template v-slot:tpy>
      <span>太平洋</span>
    </template>
  </Demo>
</template>

<script>
import Demo from "./components/Demo.vue";

export default {
  name: "App",
  components: { Demo },
  beforeCreate() {
    // console.log(`App---beforeCreate---`);
  },
  setup() {
    function showInfo(value) {
      console.log("自定义事件，显示信息", value);
    }

    return {
      showInfo,
    };
  },
};
</script>

<style>
</style>
